/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSign_upIndexRouteImport } from './routes/(auth)/sign_up/index'
import { Route as authSign_inIndexRouteImport } from './routes/(auth)/sign_in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSign_upIndexRoute = authSign_upIndexRouteImport.update({
  id: '/sign_up/',
  path: '/sign_up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSign_inIndexRoute = authSign_inIndexRouteImport.update({
  id: '/sign_in/',
  path: '/sign_in/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign_in/': typeof authSign_inIndexRoute
  '/sign_up/': typeof authSign_upIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign_in': typeof authSign_inIndexRoute
  '/sign_up': typeof authSign_upIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/sign_in/': typeof authSign_inIndexRoute
  '/(auth)/sign_up/': typeof authSign_upIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/$' | '/sign_in/' | '/sign_up/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/sign_in' | '/sign_up'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/api/auth/$'
    | '/(auth)/sign_in/'
    | '/(auth)/sign_up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign_up/': {
      id: '/(auth)/sign_up/'
      path: '/sign_up'
      fullPath: '/sign_up/'
      preLoaderRoute: typeof authSign_upIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign_in/': {
      id: '/(auth)/sign_in/'
      path: '/sign_in'
      fullPath: '/sign_in/'
      preLoaderRoute: typeof authSign_inIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authSign_inIndexRoute: typeof authSign_inIndexRoute
  authSign_upIndexRoute: typeof authSign_upIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSign_inIndexRoute: authSign_inIndexRoute,
  authSign_upIndexRoute: authSign_upIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
